### ISSUE TITLE
Default plate orientation (PiranhaGUI)

### ISSUE THREAD

**Issue by AShaw1802** [polio-nanopore/piranha#143]
The barcoded VP1 plates distributed for DDNS under the GPLN are now organised vertically to match the new ONT barcode layouts. Could the default orientation for the GUI please be set to vertical?

**Comment by rwiltonanl** [comment]
Is it possible to specify well position in the barcode.csv file in order to arrange the samples/barcodes on the html output plate as needed?  Or is there another way to specify the orientation? I use the Nanopore barcodes, and my kit has the barcodes arranged horizontally.  I'm using linux version of Piranha.  Thanks!!

**Comment by AShaw1802** [comment]
You can specify the oritentation using the "  --orientation" flag on the command line (or just select the option if using the GUI). You can also give specific coordiantes using a "well" column in the barcodes.csv.

**Comment by rwiltonanl** [comment]
Adding a "well" column worked perfectly!  I thought I saw this somewhere, but of course, once I started running this I couldn't put my finger on it!  Thanks so much for your help!!

**Comment by aineniamh** [comment]
I've changed the default now and added some more info into the readme about this functionality!
