### ISSUE TITLE
refs_present.csv output issue

### ISSUE THREAD

**Issue by ammaraziz** [polio-nanopore/piranha#149]
Hi there,

I'm trying to diagnose some issues with the output of the pipeline. One file I look at is `refs_present.csv`. I have noticed that some of the numbers don't add up or other issues.

For example, here is the output from a recent run:

```
barcode	        reference	reference_group	num_reads	percent_of_sample
barcode26	unmapped	unmapped	62935	55
barcode26	EnterovirusB84_DQ902712	NonPolioEV	475	0.42
barcode26	EnterovirusB81_AY843299	NonPolioEV	24	0.02
barcode26	Echovirus6_AY302558	NonPolioEV	43	0.04
barcode26	Echovirus17_AY302543	NonPolioEV	199	0.17
barcode26	CoxsackievirusA9_D00627	NonPolioEV	77	0.07
barcode26	EnterovirusD68_AY426531	NonPolioEV	2	0
barcode26	Echovirus14_AY302540	NonPolioEV	132	0.12
....
```

First issue I think the category `unmapped` contains filtered (min aln block, mapq < 50) and truly unmapped reads (`*`).

Second issue is the percentages don't add up to 100%. i.e. where's the other 45% of reads? I think this is related to the above issue.

I was looking at the code and found a few improvements. Would you be open to accepting a pull request for this issue?

Thanks,

Ammar

**Comment by aineniamh** [comment]
Hi @ammaraziz, just following up on this! Happy to have a look into it- but it would be very helpful if you could supply some example reads for me to check the source of this problem. As I've been developing the tool with poliovirus in mind, I haven't tested very extensively on non-polio enterovirus reads so it would be good to get a real world example to help debug!

**Comment by aineniamh** [comment]
That's no problem! I've recently worked a bit on that code and now an intermediate file is output (accessed with --no-temp flag in preprocessing outdir). This file reports for every read within the correct length cut offs what has happened to it (mapped, unmapped, filtered, why it was filtered). I haven't seen where there may have been a miscount, but we should now have every read documented- i think if there's non polio enterovirus in the sample, it could be low mapping quality scores filter out the hits because of competing references in the database. Happy to look into it though! 
My email is aine.otoole@ed.ac.uk if you want to send a sample for testing!

**Comment by aineniamh** [comment]
I'm going to close this as is stale, i've since worked on this code so may be resolved now.
