### ISSUE TITLE
Control virus sequences

### ISSUE THREAD

**Issue by AShaw1802** [polio-nanopore/piranha#188]
Hi,
The two control virus candidate sequences are in the VP1 reference database now and I've added some display names etc- could Piranha be updated to pick these up as the positive control? I think we can have both candidates lumped together for the purpose of the tables showing mapping to the positive control.
Thanks!

**Comment by rambaut** [comment]
Closing this issue and will resubmit it as a feature request.

**Comment by aineniamh** [comment]
Hey @AShaw1802, just for going forward- the way we've been trying to work is to create a branch of the repository for any new additions and then submit a pull request that will prompt another member of the organisation to vet and approve before merging into main, rather than just commiting new changes directly to main. 

This would save any changes getting incorporated into a release without us realising! 

The new references added had annotation fields that don't work with the current version of piranha (there are currently defined fields categories described in the README that those display names must be), and one of the new references was only 1 SNP away from a reference already in the database. This led to very low mapping quality scores for the positive control because there were 2 equally good matches in the database, so were getting filtered out for low mapping quality on trials in Ghana. 

Just to flag that the latest release has those new references removed to fix the above issues for the moment.
