### ISSUE TITLE
Lack of sequences from supplementary-datadir in trees generated by phylo module

### ISSUE THREAD

**Issue by AShaw1802** [polio-nanopore/piranha#224]
[ReferenceDatabase_text.txt](https://github.com/polio-nanopore/piranha/files/14496836/ReferenceDatabase_text.txt)

Hi, I'm struggling to get the phylo module to add the supplementary-datadir to the trees that are generated (both report and .tre file)- I'm using the command 

"piranha -b Demo_barcodes.csv -i demultiplexed/  -rp  -sd ReferenceDatabase/ -o Output" 

with the Piranaha v.1.2.2 and the updated conda environment. Everything is running to completion and I have the tree and report, but the sequences from the supp directory are missing. I've attached the fasta file that is in ReferenceDatabase/ which has ddns_group in the headers (Originally the file was ReferenceDatabase.fasta, which I converted to text so that I could upload it). Can you spot any error in my file or command? Thanks!

**Comment by aineniamh** [comment]
<img width="1245" alt="Screenshot 2024-03-05 at 16 46 34" src="https://github.com/polio-nanopore/piranha/assets/11678307/c46f537b-1386-4cd0-8693-1fc56e11cedb">
I'm not sure what the issue is- I just ran your command on some example data I have and they got added in fine. 
Are there Sabin2-related and Sabin1-related phylogenies being made at all? Can you attach the output?

**Comment by AShaw1802** [comment]
I did a few re-installations and cleared out the conda environments in case that made a difference, and whilst it's still the same pirahna version I got the SD sequences added in the end, so an update issue. Thanks for checking though!
