### ISSUE TITLE
Ev reads present?

### ISSUE THREAD

**Issue by Ceres90** [polio-nanopore/piranha#229]
This might not be an issue and more of just a misinterpretation of the tool but when I run piranha , the plate map at the bottom appears to say EV reads present in many of my wells but the table only shows unmapped reads , if there are EV reads should there be at least values under Nonpolioev ?    I know these samples have enteroviruses in them so I would expect Non-polio EV to show up 

![image](https://github.com/polio-nanopore/piranha/assets/95306501/87649032-a7bf-4862-bdc1-e49359120cdc)

![image](https://github.com/polio-nanopore/piranha/assets/95306501/73a07c91-ed41-4ce6-ae9d-1368e3d98d51)

**Comment by aineniamh** [comment]
Hmm, this doesn't look right- it should only show if there are reads mapped- it could be that the reads *do* map, but are being filtered out for quality reasons. If piranha is run in no-temp mode, a file is produced that tracks what happens to each read and why it's not included. 

I've got a PR that I'm working on that is more permissive of low quality divergent reads, which may resolve this. If you have a small set of reads you'd be happy to share here I can check quickly what the source of this issue is!

**Comment by aineniamh** [comment]
Thanks! 
- Okay, the first thing I realised when running was the default settings in piranha will filter out based on read length, so my first run had removed most of the reads just through read length filtering
- - I've realised that the colouring on the plot is counting the 'unmapped' read section as well, so the header should really read "Reads present" rather than EV reads specifically, but anything above the minimum read threshold will get flagged as "positive" and you can then filter by specific type with the dropdown menu (e.g. NonPolioEV will show up if it's present). 
- I changed the filter to allow reads 100bp-1300bp through, and then they were all mostly getting through to the mapping stage, but looking at the minimap2 output, there still was no hits for any of these reads. I played around with the minimap2 settings a bit (we used asm20 currently and I tried out map-ont too) and that didn't change anything. Do you know what enterovirus you're expecting to sequence? It may not be well represented in the default database.

**Comment by Ceres90** [comment]
![image](https://github.com/polio-nanopore/piranha/assets/95306501/a832a764-dc89-4d01-a8b3-9e6976025eb6)

ok that makes sense , I attached a pic of the reads I saw using epi2me

**Comment by Ceres90** [comment]
Anyone have a chance to look at why these viruses may not show up on Pirahna?

**Comment by aineniamh** [comment]
Hi, sorry for the big delay! I've merged a dev branch in that should help with this- it now has more permissive mapping settings, but also will mask low coverage sites that may not have reads mapping to them.
